import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: process.env.CHROMIUM });
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
const erros = [];
p.on('pageerror', (e) => erros.push(e.message));
p.on('console', (m) => { if (m.type()==='error') erros.push(m.text()); });
await p.goto('file:///home/user/Generate-/dist/documentos.html');
await p.waitForTimeout(400);
console.log('titulo:', await p.title());
console.log('documentos:', await p.locator('.documento').count());
console.log('tabelas:', await p.locator('table').count());
console.log('chips de grau:', await p.locator('.grau').count());
console.log('chips de estado:', await p.locator('.estado').count());
const largura = await p.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth);
console.log('sem rolagem horizontal:', largura ? 'sim' : 'NAO');
await p.locator('a[href="#qa-achados"]').click();
await p.waitForTimeout(300);
console.log('navegacao funciona:', (await p.evaluate(() => location.hash)) === '#qa-achados' ? 'sim' : 'NAO');
await p.screenshot({ path: '/home/user/Generate-/dist/docs-claro.png' });
await p.emulateMedia({ colorScheme: 'dark' });
await p.goto('file:///home/user/Generate-/dist/documentos.html');
await p.waitForTimeout(300);
await p.screenshot({ path: '/home/user/Generate-/dist/docs-escuro.png' });
console.log('erros:', erros.length, erros.slice(0,2).join(' | '));
await b.close();
